CREATE DATABASE CarsDb
USE CarsDb

CREATE TABLE Make (
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[Name] NVARCHAR(64) NOT NULL,
	EstablishmentDate DATE NOT NULL,
	TotalCarsMade INT DEFAULT 0,
	TotalIncome DECIMAL(19,4)
)

CREATE TABLE Model (
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	MakeId UNIQUEIDENTIFIER NOT NULL,
	ModelName NVARCHAR(64) NOT NULL,
	StartYear DATE NOT NULL,
	EndYear DATE,
	Price DECIMAL(19,4) NOT NULL,
	TotalModelsMade INT DEFAULT 0,
	CONSTRAINT FK_MakeModel FOREIGN KEY (MakeId)
	REFERENCES Make(Id)
)

CREATE TABLE Engine (
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	ModelId UNIQUEIDENTIFIER NOT NULL,
	EngineCode NVARCHAR(64) NOT NULL,
	HorsePower INT NOT NULL,
	Torque INT NOT NULL,
	Fuel NVARCHAR(64),
	HasTurbo BIT NOT NULL DEFAULT 0,
	CONSTRAINT FK_EngineModel FOREIGN KEY (ModelId)
	REFERENCES Model(Id)
)

CREATE TABLE Users (
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	Username NVARCHAR(32) NOT NULL,
	[Password] NVARCHAR(1024) NOT NULL,
	IsAdmin BIT DEFAULT 0 NOT NULL
)